### ISSUE TITLE
Where is source code for p1touch.bin

### ISSUE THREAD

**Issue by cjsieh** [xperiments/p1touch#2]
I would like to use this on the 3.5 version of this board.  Need source code to make that happen.

Thanks

**Comment by xperiments** [comment]
I will open the code when I get home from vacation... Will be first
September week.. no P1P with me...

**Comment by andypiper** [comment]
FWIW this is at least partially working on the X1C (currently running some tests to see what might be missing), would love to see the source and help to contribute here, when you are back and able to share it.

**Comment by TackleBerryCrash** [comment]
Config reset on sleep is a show stopper for this but this is a great start.

**Comment by psiberfunk** [comment]
> Why would you want to use this on the x1 ?

**Comment by jonnywatchbox** [comment]
did anyone get the 3.5 screen working?

**Comment by Milkman337** [comment]
Any updates will the source be uploaded now its september

**Comment by nurtext** [comment]
Friendly reminder from my side, too. I'd like to have a look at the source and compile it myself. The project would heavily benefit from releasing the source though...

**Comment by nurtext** [comment]
@xperiments Any news on this topic?

**Comment by xperiments** [comment]
Yes, I have a real Live... When it's published it's published. Don't ask more...

**Comment by nurtext** [comment]
No need to be salty.

**Comment by TackleBerryCrash** [comment]
no need to be antsy, needy, rude.... 

It will be here when it will be here. Beta testing continues. You can move along if you cant wait.

**Comment by psiberfunk** [comment]
I would generally say yes.. but "antsy" is fair with closed source things you put on your network .  I, and many others can't use this until I can see the source and verify it's not laced with phone-home malware.

**Comment by TackleBerryCrash** [comment]
Yes, you are right it was a resonabnle request and answer was given numberous times no need to beat the dead horse again and again and being borderline rude but at the same time nobody is forcing this to anyone. 
anyone not trusting this ( I would not obviously if wasnt seen the code itself and collaborated) can stroll past this repo. 
again no one is forcing anyone to install this. I know first hand dev is really pouring into this for weeks.

he is being rude and you know he is being rude too :) 

I think code will be released soon.

**Comment by psiberfunk** [comment]
> Yes, you are right it was a resonabnle request and answer was given numberous times no need to beat the dead horse again and again and being borderline rude but at the same time nobody is forcing this to anyone. anyone not trusting this ( I would not obviously if wasnt seen the code itself and collaborated) can stroll past this repo. again no one is forcing anyone to install this. I know first hand dev is really pouring into this for weeks.
> 
> he is being rude and you know he is being rude too :)
> 
> I think code will be released soon but my answer is it will be released when it is released.

Perhaps I interpret it differently.  I didn't take it as rude... but pestering perhaps :).  Sometimes people just need reminders is all.  Anyhow, i'm sure we can all move on peaceably without a flame war.

**Comment by TackleBerryCrash** [comment]
I am too old for flame wars TBH :)

**Comment by nurtext** [comment]
@TackleBerryCrash If I was meant: I didn't want to be rude and I don't consider myself a rude guy. I was just asking, because @xperiments told anyone asking the source to be released in the first week of september. 

However, @xperiments behavior isn't very professionell nor polite. I mean: Yes, he's a private person, but he decided to go public with his work the moment he released the binary blob as well as instructions. There's also a lot going on on Printables regarding housings for the touchscreen. So I guess the downloads are much higher than the commentors or software devs checking this repo regularely. 

My final thoughs on this are: If you decide to publish something and making promises for releasing the source code: Do it or don't. I even don't know why he closes the issue, because it hasn't been resolved so far and the request remains.

**Comment by TackleBerryCrash** [comment]
Sir, you can move on, it will be released when released.
be more professional than him and code your own and release it yourself.
you had a valid concern but pestering the dev is not cool.

Lets end this here. 
Wait if you can if not toodaloo, bon voyage,  auf wiedersehen....

Issue is closed b/c answer is given but you dont get the answer apparently

**Comment by xperiments** [comment]
Code will be published next week, we are currently checking beta feedback.

@nurtext yes I have been a little rude, I am sorry
@psiberfunk @nurtext I see your points and are normal but this does not make me unprofessional. As commented I have a life, the plan was to release on vacation return but life... 

BTW I see things another way.. if you needed in a hurry to see the code just DM me as @TackleBerryCrash done. Him has been able to access code since some time...

**Comment by Milkman337** [comment]
quick question where can I DM you @xperiments

**Comment by xperiments** [comment]
@xps3riments / @xperiments in twitter

**Comment by DIYLAB-DE** [comment]
I don't use Twitter - may I still have a look at your sources in an appropriate way? 
Best, Bruno

**Comment by Milkman337** [comment]
I also dont have a twitter and would like to take a look too

**Comment by xperiments** [comment]
This monday will be open

**Comment by Arnos-Kramkiste** [comment]
any newer bin file or beta versions to test ? my screen turn off after some seconds and so on

**Comment by xperiments** [comment]
https://github.com/xperiments-in/xtouch
